# Generated by Django 5.2.3 on 2025-06-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura')),
                ('sensacao_termica', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Sensação Térmica')),
                ('direcao_vento', models.CharField(max_length=3, verbose_name='Direção do Vento')),
                ('velocidade_vento', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Velocidade do Vento')),
                ('umidade', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Umidade do Ar')),
                ('pressao', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Pressão Atmosférica')),
                ('cobertura_nuvem', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cobertura de Nuvem')),
            ],
        ),
        migrations.CreateModel(
            name='Hoje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Dia de Hoje')),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura Máxima')),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura Mínima')),
            ],
        ),
        migrations.CreateModel(
            name='ProximosDias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia')),
                ('chance_chuva', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Chance de chuva')),
                ('cobertura_nuvem', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cobertura de Nuvem')),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura Máxima')),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura Mínima')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperatura')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.hoje')),
            ],
        ),
    ]
