# Generated by Django 5.2.3 on 2025-06-17 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agora',
            options={'verbose_name': 'Agora', 'verbose_name_plural': 'Agora'},
        ),
        migrations.AlterModelOptions(
            name='hoje',
            options={'verbose_name': 'Hoje', 'verbose_name_plural': 'Hoje'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterModelOptions(
            name='proximosdias',
            options={'verbose_name': 'Próximo dia', 'verbose_name_plural': 'Próximos dias'},
        ),
        migrations.AddField(
            model_name='agora',
            name='hora_coleta',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Horário da Coleta'),
            preserve_default=False,
        ),
    ]
