# Generated by Django 5.2.3 on 2025-06-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_agora_options_alter_hoje_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agora',
            name='cobertura_nuvem',
        ),
        migrations.AddField(
            model_name='agora',
            name='codigo_tempo',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=4, verbose_name='Código do tempo'),
            preserve_default=False,
        ),
    ]
