# Generated by Django 5.2.3 on 2025-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_remove_agora_cobertura_nuvem_agora_codigo_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proximosdias',
            name='cobertura_nuvem',
        ),
        migrations.AddField(
            model_name='proximosdias',
            name='codigo_tempo',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=4, verbose_name='Código do tempo'),
            preserve_default=False,
        ),
    ]
