# Generated by Django 5.2.3 on 2025-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_remove_proximosdias_cobertura_nuvem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cidade')),
                ('regiao', models.CharField(max_length=100, verbose_name='Região')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('timezone', models.CharField(max_length=100, verbose_name='Fuso Horário')),
            ],
        ),
        migrations.DeleteModel(
            name='Agora',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.DeleteModel(
            name='ProximosDias',
        ),
        migrations.DeleteModel(
            name='Hoje',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
