# Generated by Django 5.2.3 on 2025-06-21 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_cidade_delete_agora_remove_horario_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='nomeAPI',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Nome da cidade na API'),
            preserve_default=False,
        ),
    ]
